server:
  port: 8200
spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true #注册的时候使用ip地址的方式进行注册
  client:
    service-url:
      defultZone: http://localhost:8761/eureka/ #默认http://localhost:8761/eureka/