server:
  port: 8085
spring:
  application:
    name: sentinel-learn
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'