server:
  port: 18085
spring:
  application:
    name: sentinel-learn
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true