server:
  port: 18085
spring:
  application:
    name: sentinel-learn
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  #sentinel:
  #  enabled: true
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
        # 错误比率
        errorThresholdPercentage: 10
        # 最小请求次数
        requestVolumeThreshold: 3
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
