server:
  port: 9002

spring:
  application:
    name: admin-client
  #不通过eureka进行SpringBoot项目监控
  #boot:
  # admin:
  #    client:
  #      url: localhost:9001
  boot:
    admin:
      client:
        password:
        username:
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #eureka是否显示ip
    prefer-ip-address: true
    #eureka 上显示的名称
    instance-id: admin-client


#暴露全部端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
