server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称 在hosts中 127.0.0.1 eureka7001.com  域名映射
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心,我的职责是维护服务实例,并不需要检索服务
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
