spring:
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        driver-class-name: com.mysql.jdbc.Driver
        password: 5EYcHss4
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://121.36.136.81:3306/ds0?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        password: 5EYcHss4
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://121.36.136.81:3306/ds1?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
      ds2:
        driver-class-name: com.mysql.jdbc.Driver
        password: 5EYcHss4
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://121.36.136.81:3306/ds2?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
    sharding:
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{id % 3}
          sharding-column: id
      tables:
        order:
          actual-data-nodes: ds$->{0..2}.order$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: order$->{order_no % 2}
              sharding-column: order_no
