server:
  port: 8003
spring:
  application:
    name: provide-game
# Discovery Server Access
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #eureka显示ip
    prefer-ip-address: true
    #eureka status的显示的名字
    instance-id: provide-game-8003

#项目监控配置  具体看印象笔记  自定义info config
management:
  endpoint:
    info:
      enabled: true
#自定义info信息
info:
  app:
    encoding: UTF-8
    java.source: 1.8
    java.traget: 1.8
