server:
  port: 8761
eureka:
  instance:
    namespace: eureka-server #eureka实例的主机名
  client:
    fetch-registry: false #false不从eureka上来获得服务的注册信息(默认true)
    register-with-eureka: false #false不把自己注册到注册中心eureka (默认true)
    service-url:
      defultZone: http://localhost:8761/eureka/ #默认http://localhost:8761/eureka/
    region: