server:
  port: 18080
spring:
  application:
    name: sca-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.136.81:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 5EYcHss4
  cloud:
    alibaba:
      seata:
        tx-service-group: sca-provider-seata-tx-service-group


mybatis:
  mapper-locations: classpath:mapper/*.xml
