server:
  port: 18081
spring:
  application:
    name: comsumer-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.136.81:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 5EYcHss4
  cloud:
    alibaba:
      seata:
        tx-service-group: sca-consumer-seata-tx-service-group


mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  config:
    type: nacos
    nacos:
      server-addr: 121.36.162.179:8848
      group : "SEATA_GROUP"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 121.36.162.179:8848
      group : "SEATA_GROUP"