server:
  port: 9527
spring:
  application:
    name: ZUUL-GATEWAY
# 服务网关也要注册为一个微服务
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #eureka显示ip
    prefer-ip-address: true
    #eureka status的显示的名字
    instance-id: gateway-9527.com

#项目监控配置  具体看印象笔记  自定义info config
management:
  endpoint:
    info:
      enabled: true
#自定义info信息
info:
  app:
    encoding: UTF-8
    java.source: 1.8
    java.traget: 1.8
    version: $project.version$

#如果下面的啥都配置的话  访问 provide-game 只能通过http://localhost:9527/provide-game/**
#而不能通过直接请求 http://localhost:8001/** 相当于接收全部的请求并且转发 并可以在这部添加权限校验
#增加了服务的安全性

#自定义服务映射规则
zuul:
  routes:
    #服务名          映射地址  http://localhost:9527/test/game/1
    PROVIDE-GAME:  /test/**
  #忽略原来真实名字    这样就访问不了了 http://localhost:9527/provide-game/game/1
  ignored-services: "*"
  #统一前缀
  prefix: /syj


